In [1]:
import pandas as pd
import numpy as np

from IPython.display import display

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 120)

In [2]:
df = pd.read_csv("House Prices.csv")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

display(df.head())

Dataset loaded successfully!
Rows: 1460
Columns: 81

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
print("Dataset Shape:", df.shape)
print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
display(df.dtypes.to_frame("Data Type"))

print("\nDataset Information:")
df.info()

Dataset Shape: (1460, 81)

Column Names:
['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice']

Data Types:

              Data Type
Id                int64
MSSubClass        int64
MSZoning            str
LotFrontage     float64
LotArea           int64
Street              str
Alley               str
LotShape            str
LandContour         str
Utilities           str
LotConfig           str
LandSlope           str
Neighborhood        str
Condition1          str
Condition2          str
BldgType            str
HouseStyle          str
OverallQual       int64
OverallCond       int64
YearBuilt         int64
YearRemodAdd      int64
RoofStyle           str
RoofMatl            str
Exterior1st         str
Exterior2nd         str
MasVnrType          str
MasVnrArea      float64
ExterQual           str
ExterCond           str
Foundation          str
BsmtQual            str
BsmtCond            str
BsmtExposure        str
BsmtFinType1        str
BsmtFinSF1        int64
BsmtFinType2        str
BsmtFinSF2        int64
BsmtUnfSF         int64
TotalBsmtSF       int64
Heating             str
HeatingQC           str
CentralAir          str
Electrical          str
1stFlrSF          int64
2ndFlrSF          int64
LowQualFinSF      int64
GrLivArea         int64
BsmtFullBath      int64
BsmtHalfBath      int64
FullBath          int64
HalfBath          int64
BedroomAbvGr      int64
KitchenAbvGr      int64
KitchenQual         str
TotRmsAbvGrd      int64
Functional          str
Fireplaces        int64
FireplaceQu         str
GarageType          str
GarageYrBlt     float64
GarageFinish        str
GarageCars        int64
GarageArea        int64
GarageQual          str
GarageCond          str
PavedDrive          str
WoodDeckSF        int64
OpenPorchSF       int64
EnclosedPorch     int64
3SsnPorch         int64
ScreenPorch       int64
PoolArea          int64
PoolQC              str
Fence               str
MiscFeature         str
MiscVal           int64
MoSold            int64
YrSold            int64
SaleType            str
SaleCondition       str
SalePrice         int64

Dataset Information:
<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB

In [4]:
# Missing values
missing_count = df.isnull().sum()
missing_percent = (missing_count / len(df)) * 100

# Data types
data_types = df.dtypes.astype(str)

# Unique values
unique_values = df.nunique()

quality_report = pd.DataFrame({
    "Data_Type": data_types,
    "Missing_Count": missing_count,
    "Missing_Percent": missing_percent.round(2),
    "Unique_Values": unique_values
})

quality_report = quality_report.sort_values(
    by="Missing_Count",
    ascending=False
)

print("Duplicate rows:", df.duplicated().sum())

display(quality_report)

Duplicate rows: 0

              Data_Type  Missing_Count  Missing_Percent  Unique_Values
PoolQC              str           1453            99.52              3
MiscFeature         str           1406            96.30              4
Alley               str           1369            93.77              2
Fence               str           1179            80.75              4
MasVnrType          str            872            59.73              3
FireplaceQu         str            690            47.26              5
LotFrontage     float64            259            17.74            110
GarageYrBlt     float64             81             5.55             97
GarageCond          str             81             5.55              5
GarageType          str             81             5.55              6
GarageFinish        str             81             5.55              3
GarageQual          str             81             5.55              5
BsmtFinType2        str             38             2.60              6
BsmtExposure        str             38             2.60              4
BsmtQual            str             37             2.53              4
BsmtCond            str             37             2.53              4
BsmtFinType1        str             37             2.53              6
MasVnrArea      float64              8             0.55            327
Electrical          str              1             0.07              5
Id                int64              0             0.00           1460
Functional          str              0             0.00              7
Fireplaces        int64              0             0.00              4
KitchenQual         str              0             0.00              4
KitchenAbvGr      int64              0             0.00              4
BedroomAbvGr      int64              0             0.00              8
HalfBath          int64              0             0.00              3
FullBath          int64              0             0.00              4
BsmtHalfBath      int64              0             0.00              3
TotRmsAbvGrd      int64              0             0.00             12
GarageCars        int64              0             0.00              5
GrLivArea         int64              0             0.00            861
GarageArea        int64              0             0.00            441
PavedDrive          str              0             0.00              3
WoodDeckSF        int64              0             0.00            274
OpenPorchSF       int64              0             0.00            202
EnclosedPorch     int64              0             0.00            120
3SsnPorch         int64              0             0.00             20
ScreenPorch       int64              0             0.00             76
PoolArea          int64              0             0.00              8
MiscVal           int64              0             0.00             21
MoSold            int64              0             0.00             12
YrSold            int64              0             0.00              5
SaleType            str              0             0.00              9
SaleCondition       str              0             0.00              6
BsmtFullBath      int64              0             0.00              4
HeatingQC           str              0             0.00              5
LowQualFinSF      int64              0             0.00             24
LandSlope           str              0             0.00              3
OverallQual       int64              0             0.00             10
HouseStyle          str              0             0.00              8
BldgType            str              0             0.00              5
Condition2          str              0             0.00              8
Condition1          str              0             0.00              9
Neighborhood        str              0             0.00             25
LotConfig           str              0             0.00              5
YearBuilt         int64              0             0.00            112
Utilities           str              0             0.00              2
LandContour         str              0             0.00              4
LotShape            str              0             0.00              4
Street              str              0             0.00              2
LotArea           int64              0             0.00           1073
MSZoning            str              0             0.00              5
OverallCond       int64              0             0.00              9
YearRemodAdd      int64              0             0.00             61
2ndFlrSF          int64              0             0.00            417
BsmtFinSF2        int64              0             0.00            144
1stFlrSF          int64              0             0.00            753
CentralAir          str              0             0.00              2
MSSubClass        int64              0             0.00             15
Heating             str              0             0.00              6
TotalBsmtSF       int64              0             0.00            721
BsmtUnfSF         int64              0             0.00            780
BsmtFinSF1        int64              0             0.00            637
RoofStyle           str              0             0.00              6
Foundation          str              0             0.00              6
ExterCond           str              0             0.00              5
ExterQual           str              0             0.00              4
Exterior2nd         str              0             0.00             16
Exterior1st         str              0             0.00             15
RoofMatl            str              0             0.00              8
SalePrice         int64              0             0.00            663

In [5]:
missing_report = quality_report[
    quality_report["Missing_Count"] > 0
]

display(missing_report)

             Data_Type  Missing_Count  Missing_Percent  Unique_Values
PoolQC             str           1453            99.52              3
MiscFeature        str           1406            96.30              4
Alley              str           1369            93.77              2
Fence              str           1179            80.75              4
MasVnrType         str            872            59.73              3
FireplaceQu        str            690            47.26              5
LotFrontage    float64            259            17.74            110
GarageYrBlt    float64             81             5.55             97
GarageCond         str             81             5.55              5
GarageType         str             81             5.55              6
GarageFinish       str             81             5.55              3
GarageQual         str             81             5.55              5
BsmtFinType2       str             38             2.60              6
BsmtExposure       str             38             2.60              4
BsmtQual           str             37             2.53              4
BsmtCond           str             37             2.53              4
BsmtFinType1       str             37             2.53              6
MasVnrArea     float64              8             0.55            327
Electrical         str              1             0.07              5

In [6]:
numeric_columns = df.select_dtypes(include=np.number).columns

range_report = pd.DataFrame({
    "Min": df[numeric_columns].min(),
    "Q1": df[numeric_columns].quantile(0.25),
    "Median": df[numeric_columns].median(),
    "Q3": df[numeric_columns].quantile(0.75),
    "Max": df[numeric_columns].max()
})

display(range_report)

                   Min         Q1    Median         Q3       Max
Id                 1.0     365.75     730.5    1095.25    1460.0
MSSubClass        20.0      20.00      50.0      70.00     190.0
LotFrontage       21.0      59.00      69.0      80.00     313.0
LotArea         1300.0    7553.50    9478.5   11601.50  215245.0
OverallQual        1.0       5.00       6.0       7.00      10.0
OverallCond        1.0       5.00       5.0       6.00       9.0
YearBuilt       1872.0    1954.00    1973.0    2000.00    2010.0
YearRemodAdd    1950.0    1967.00    1994.0    2004.00    2010.0
MasVnrArea         0.0       0.00       0.0     166.00    1600.0
BsmtFinSF1         0.0       0.00     383.5     712.25    5644.0
BsmtFinSF2         0.0       0.00       0.0       0.00    1474.0
BsmtUnfSF          0.0     223.00     477.5     808.00    2336.0
TotalBsmtSF        0.0     795.75     991.5    1298.25    6110.0
1stFlrSF         334.0     882.00    1087.0    1391.25    4692.0
2ndFlrSF           0.0       0.00       0.0     728.00    2065.0
LowQualFinSF       0.0       0.00       0.0       0.00     572.0
GrLivArea        334.0    1129.50    1464.0    1776.75    5642.0
BsmtFullBath       0.0       0.00       0.0       1.00       3.0
BsmtHalfBath       0.0       0.00       0.0       0.00       2.0
FullBath           0.0       1.00       2.0       2.00       3.0
HalfBath           0.0       0.00       0.0       1.00       2.0
BedroomAbvGr       0.0       2.00       3.0       3.00       8.0
KitchenAbvGr       0.0       1.00       1.0       1.00       3.0
TotRmsAbvGrd       2.0       5.00       6.0       7.00      14.0
Fireplaces         0.0       0.00       1.0       1.00       3.0
GarageYrBlt     1900.0    1961.00    1980.0    2002.00    2010.0
GarageCars         0.0       1.00       2.0       2.00       4.0
GarageArea         0.0     334.50     480.0     576.00    1418.0
WoodDeckSF         0.0       0.00       0.0     168.00     857.0
OpenPorchSF        0.0       0.00      25.0      68.00     547.0
EnclosedPorch      0.0       0.00       0.0       0.00     552.0
3SsnPorch          0.0       0.00       0.0       0.00     508.0
ScreenPorch        0.0       0.00       0.0       0.00     480.0
PoolArea           0.0       0.00       0.0       0.00     738.0
MiscVal            0.0       0.00       0.0       0.00   15500.0
MoSold             1.0       5.00       6.0       8.00      12.0
YrSold          2006.0    2007.00    2008.0    2009.00    2010.0
SalePrice      34900.0  129975.00  163000.0  214000.00  755000.0

In [7]:
before_rows = len(df)
before_duplicates = df.duplicated().sum()
before_nulls = df.isnull().sum().sum()

before_dtypes = df.dtypes.astype(str).to_dict()

print("BEFORE CLEANING")
print("----------------")
print("Rows:", before_rows)
print("Total missing values:", before_nulls)
print("Duplicate rows:", before_duplicates)

BEFORE CLEANING
----------------
Rows: 1460
Total missing values: 7829
Duplicate rows: 0

## Missing Data Handling Strategy

The missing values are handled according to the meaning of each variable rather than applying one method to every column.

- **Categorical columns describing the absence of a feature** such as `Alley`, `BsmtQual`, `BsmtCond`, `BsmtExposure`, `BsmtFinType1`, `BsmtFinType2`, `FireplaceQu`, `GarageType`, `GarageFinish`, `GarageQual`, `GarageCond`, `PoolQC`, `Fence`, `MiscFeature`, and `MasVnrType` are filled with `"None"` because a missing value indicates that the house does not have that feature.

- **Numeric columns representing the size/capacity of an absent feature**, such as `MasVnrArea`, `BsmtFinSF1`, `BsmtFinSF2`, `BsmtUnfSF`, `TotalBsmtSF`, `BsmtFullBath`, `BsmtHalfBath`, `GarageCars`, and `GarageArea`, are filled with `0` when appropriate because no feature means zero area/capacity.

- `LotFrontage` is filled using the **median LotFrontage within each Neighborhood**. This preserves local housing characteristics and is more appropriate than using one global value.

- `GarageYrBlt` is filled with `0` when there is no garage. For remaining missing values, the median is used.

- `Electrical` has only a very small number of missing values, so the **mode** is used because it is a categorical variable.

This approach avoids unnecessary row deletion and preserves as much information as possible.

In [8]:
cleaned_df = df.copy()

print("Created a copy for cleaning.")

Created a copy for cleaning.

In [9]:
categorical_none_columns = [
    "Alley",
    "MasVnrType",
    "BsmtQual",
    "BsmtCond",
    "BsmtExposure",
    "BsmtFinType1",
    "BsmtFinType2",
    "FireplaceQu",
    "GarageType",
    "GarageFinish",
    "GarageQual",
    "GarageCond",
    "PoolQC",
    "Fence",
    "MiscFeature"
]

for column in categorical_none_columns:
    if column in cleaned_df.columns:
        cleaned_df[column] = cleaned_df[column].fillna("None")

print("Categorical missing values handled.")

Categorical missing values handled.

In [10]:
zero_fill_columns = [
    "MasVnrArea",
    "BsmtFinSF1",
    "BsmtFinSF2",
    "BsmtUnfSF",
    "TotalBsmtSF",
    "BsmtFullBath",
    "BsmtHalfBath",
    "GarageCars",
    "GarageArea"
]

for column in zero_fill_columns:
    if column in cleaned_df.columns:
        cleaned_df[column] = cleaned_df[column].fillna(0)

print("Feature-related numerical missing values filled with 0.")

Feature-related numerical missing values filled with 0.

In [11]:
cleaned_df["LotFrontage"] = (
    cleaned_df.groupby("Neighborhood")["LotFrontage"]
    .transform(lambda x: x.fillna(x.median()))
)

# If any values are still missing, use the overall median
cleaned_df["LotFrontage"] = cleaned_df["LotFrontage"].fillna(
    cleaned_df["LotFrontage"].median()
)

print("LotFrontage missing values handled using neighborhood median.")

LotFrontage missing values handled using neighborhood median.

In [12]:
# Houses without a garage are represented as 0
cleaned_df.loc[
    cleaned_df["GarageType"] == "None",
    "GarageYrBlt"
] = 0

# Any remaining missing values use the median
garage_year_median = cleaned_df.loc[
    cleaned_df["GarageYrBlt"] > 0,
    "GarageYrBlt"
].median()

cleaned_df["GarageYrBlt"] = cleaned_df["GarageYrBlt"].fillna(
    garage_year_median
)

print("GarageYrBlt missing values handled.")

GarageYrBlt missing values handled.

In [13]:
electrical_mode = cleaned_df["Electrical"].mode()[0]

cleaned_df["Electrical"] = cleaned_df["Electrical"].fillna(
    electrical_mode
)

print("Electrical missing values filled with mode:", electrical_mode)

Electrical missing values filled with mode: SBrkr

In [14]:
remaining_missing = cleaned_df.isnull().sum()

remaining_missing = remaining_missing[
    remaining_missing > 0
].sort_values(ascending=False)

print("Remaining missing values:")

if len(remaining_missing) == 0:
    print("No missing values remain.")
else:
    display(remaining_missing)

Remaining missing values:
No missing values remain.

In [15]:
duplicates_before = cleaned_df.duplicated().sum()

print("Duplicate rows found:", duplicates_before)

cleaned_df = cleaned_df.drop_duplicates()

duplicates_after = cleaned_df.duplicated().sum()

print("Duplicate rows after removal:", duplicates_after)
print("Rows after duplicate removal:", len(cleaned_df))

Duplicate rows found: 0
Duplicate rows after removal: 0
Rows after duplicate removal: 1460

In [16]:
# Identify categorical columns
categorical_columns = cleaned_df.select_dtypes(
    include=["object"]
).columns

# Remove leading/trailing whitespace
for column in categorical_columns:
    cleaned_df[column] = cleaned_df[column].str.strip()

# Convert empty strings to NaN
for column in categorical_columns:
    cleaned_df[column] = cleaned_df[column].replace("", np.nan)

# Check if standardization introduced any missing values
print("Missing values after standardization:")
print(cleaned_df.isnull().sum().sum())

Missing values after standardization:
0

/var/folders/cl/kwk343bj1n37tj6y42flyvk80000gn/T/ipykernel_12239/1142499717.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = cleaned_df.select_dtypes(

## Data Standardisation

The categorical variables were checked for inconsistent formatting.

The dataset mainly uses standardized categorical codes such as `RL`, `RM`, `Pave`, `Gd`, `TA`, and `Normal`. Therefore, these values were not unnecessarily renamed because the codes have meaningful dataset-specific definitions.

Leading and trailing whitespace was removed from categorical columns, and empty strings were treated as missing values.

There are no actual date columns in the dataset requiring conversion to `datetime`. The variables `YearBuilt`, `YearRemodAdd`, `GarageYrBlt`, and `YrSold` represent years and are therefore retained as numeric year values.

In [17]:
# ID should be treated as an identifier, not a numerical measurement
cleaned_df["Id"] = cleaned_df["Id"].astype(str)

# MSSubClass is a housing classification code rather than a continuous measurement
cleaned_df["MSSubClass"] = cleaned_df["MSSubClass"].astype(str)

# SalePrice is a monetary value
cleaned_df["SalePrice"] = cleaned_df["SalePrice"].astype(float)

print("Data types after correction:")
display(cleaned_df.dtypes.to_frame("Data Type"))

Data types after correction:

              Data Type
Id                  str
MSSubClass          str
MSZoning            str
LotFrontage     float64
LotArea           int64
Street              str
Alley               str
LotShape            str
LandContour         str
Utilities           str
LotConfig           str
LandSlope           str
Neighborhood        str
Condition1          str
Condition2          str
BldgType            str
HouseStyle          str
OverallQual       int64
OverallCond       int64
YearBuilt         int64
YearRemodAdd      int64
RoofStyle           str
RoofMatl            str
Exterior1st         str
Exterior2nd         str
MasVnrType          str
MasVnrArea      float64
ExterQual           str
ExterCond           str
Foundation          str
BsmtQual            str
BsmtCond            str
BsmtExposure        str
BsmtFinType1        str
BsmtFinSF1        int64
BsmtFinType2        str
BsmtFinSF2        int64
BsmtUnfSF         int64
TotalBsmtSF       int64
Heating             str
HeatingQC           str
CentralAir          str
Electrical          str
1stFlrSF          int64
2ndFlrSF          int64
LowQualFinSF      int64
GrLivArea         int64
BsmtFullBath      int64
BsmtHalfBath      int64
FullBath          int64
HalfBath          int64
BedroomAbvGr      int64
KitchenAbvGr      int64
KitchenQual         str
TotRmsAbvGrd      int64
Functional          str
Fireplaces        int64
FireplaceQu         str
GarageType          str
GarageYrBlt     float64
GarageFinish        str
GarageCars        int64
GarageArea        int64
GarageQual          str
GarageCond          str
PavedDrive          str
WoodDeckSF        int64
OpenPorchSF       int64
EnclosedPorch     int64
3SsnPorch         int64
ScreenPorch       int64
PoolArea          int64
PoolQC              str
Fence               str
MiscFeature         str
MiscVal           int64
MoSold            int64
YrSold            int64
SaleType            str
SaleCondition       str
SalePrice       float64

In [18]:
print("Id data type:", cleaned_df["Id"].dtype)
print("MSSubClass data type:", cleaned_df["MSSubClass"].dtype)
print("SalePrice data type:", cleaned_df["SalePrice"].dtype)

Id data type: str
MSSubClass data type: str
SalePrice data type: float64

In [19]:
# Select numeric columns
numeric_columns = cleaned_df.select_dtypes(
    include=np.number
).columns

outlier_summary = []

for column in numeric_columns:

    Q1 = cleaned_df[column].quantile(0.25)
    Q3 = cleaned_df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = cleaned_df[
        (cleaned_df[column] < lower_bound) |
        (cleaned_df[column] > upper_bound)
    ]

    outlier_summary.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower_Bound": lower_bound,
        "Upper_Bound": upper_bound,
        "Outlier_Count": len(outliers)
    })

outlier_report = pd.DataFrame(outlier_summary)

outlier_report = outlier_report.sort_values(
    by="Outlier_Count",
    ascending=False
)

display(outlier_report)

           Column         Q1         Q3       IQR  Lower_Bound  Upper_Bound  Outlier_Count
28  EnclosedPorch       0.00       0.00      0.00        0.000        0.000            208
8      BsmtFinSF2       0.00       0.00      0.00        0.000        0.000            167
3     OverallCond       5.00       6.00      1.00        3.500        7.500            125
30    ScreenPorch       0.00       0.00      0.00        0.000        0.000            116
6      MasVnrArea       0.00     164.25    164.25     -246.375      410.625             98
0     LotFrontage      60.00      80.00     20.00       30.000      110.000             93
16   BsmtHalfBath       0.00       0.00      0.00        0.000        0.000             82
23    GarageYrBlt    1958.00    2001.00     43.00     1893.500     2065.500             81
27    OpenPorchSF       0.00      68.00     68.00     -102.000      170.000             77
1         LotArea    7553.50   11601.50   4048.00     1481.500    17673.500             69
20   KitchenAbvGr       1.00       1.00      0.00        1.000        1.000             68
35      SalePrice  129975.00  214000.00  84025.00     3937.500   340037.500             61
10    TotalBsmtSF     795.75    1298.25    502.50       42.000     2052.000             61
32        MiscVal       0.00       0.00      0.00        0.000        0.000             52
19   BedroomAbvGr       2.00       3.00      1.00        0.500        4.500             35
26     WoodDeckSF       0.00     168.00    168.00     -252.000      420.000             32
14      GrLivArea    1129.50    1776.75    647.25      158.625     2747.625             31
21   TotRmsAbvGrd       5.00       7.00      2.00        2.000       10.000             30
9       BsmtUnfSF     223.00     808.00    585.00     -654.500     1685.500             29
13   LowQualFinSF       0.00       0.00      0.00        0.000        0.000             26
29      3SsnPorch       0.00       0.00      0.00        0.000        0.000             24
25     GarageArea     334.50     576.00    241.50      -27.750      938.250             21
11       1stFlrSF     882.00    1391.25    509.25      118.125     2155.125             20
4       YearBuilt    1954.00    2000.00     46.00     1885.000     2069.000              7
7      BsmtFinSF1       0.00     712.25    712.25    -1068.375     1780.625              7
31       PoolArea       0.00       0.00      0.00        0.000        0.000              7
22     Fireplaces       0.00       1.00      1.00       -1.500        2.500              5
24     GarageCars       1.00       2.00      1.00       -0.500        3.500              5
2     OverallQual       5.00       7.00      2.00        2.000       10.000              2
12       2ndFlrSF       0.00     728.00    728.00    -1092.000     1820.000              2
15   BsmtFullBath       0.00       1.00      1.00       -1.500        2.500              1
5    YearRemodAdd    1967.00    2004.00     37.00     1911.500     2059.500              0
17       FullBath       1.00       2.00      1.00       -0.500        3.500              0
33         MoSold       5.00       8.00      3.00        0.500       12.500              0
34         YrSold    2007.00    2009.00      2.00     2004.000     2012.000              0
18       HalfBath       0.00       1.00      1.00       -1.500        2.500              0

In [20]:
outliers_only = outlier_report[
    outlier_report["Outlier_Count"] > 0
]

display(outliers_only)

           Column         Q1         Q3       IQR  Lower_Bound  Upper_Bound  Outlier_Count
28  EnclosedPorch       0.00       0.00      0.00        0.000        0.000            208
8      BsmtFinSF2       0.00       0.00      0.00        0.000        0.000            167
3     OverallCond       5.00       6.00      1.00        3.500        7.500            125
30    ScreenPorch       0.00       0.00      0.00        0.000        0.000            116
6      MasVnrArea       0.00     164.25    164.25     -246.375      410.625             98
0     LotFrontage      60.00      80.00     20.00       30.000      110.000             93
16   BsmtHalfBath       0.00       0.00      0.00        0.000        0.000             82
23    GarageYrBlt    1958.00    2001.00     43.00     1893.500     2065.500             81
27    OpenPorchSF       0.00      68.00     68.00     -102.000      170.000             77
1         LotArea    7553.50   11601.50   4048.00     1481.500    17673.500             69
20   KitchenAbvGr       1.00       1.00      0.00        1.000        1.000             68
35      SalePrice  129975.00  214000.00  84025.00     3937.500   340037.500             61
10    TotalBsmtSF     795.75    1298.25    502.50       42.000     2052.000             61
32        MiscVal       0.00       0.00      0.00        0.000        0.000             52
19   BedroomAbvGr       2.00       3.00      1.00        0.500        4.500             35
26     WoodDeckSF       0.00     168.00    168.00     -252.000      420.000             32
14      GrLivArea    1129.50    1776.75    647.25      158.625     2747.625             31
21   TotRmsAbvGrd       5.00       7.00      2.00        2.000       10.000             30
9       BsmtUnfSF     223.00     808.00    585.00     -654.500     1685.500             29
13   LowQualFinSF       0.00       0.00      0.00        0.000        0.000             26
29      3SsnPorch       0.00       0.00      0.00        0.000        0.000             24
25     GarageArea     334.50     576.00    241.50      -27.750      938.250             21
11       1stFlrSF     882.00    1391.25    509.25      118.125     2155.125             20
4       YearBuilt    1954.00    2000.00     46.00     1885.000     2069.000              7
7      BsmtFinSF1       0.00     712.25    712.25    -1068.375     1780.625              7
31       PoolArea       0.00       0.00      0.00        0.000        0.000              7
22     Fireplaces       0.00       1.00      1.00       -1.500        2.500              5
24     GarageCars       1.00       2.00      1.00       -0.500        3.500              5
2     OverallQual       5.00       7.00      2.00        2.000       10.000              2
12       2ndFlrSF       0.00     728.00    728.00    -1092.000     1820.000              2
15   BsmtFullBath       0.00       1.00      1.00       -1.500        2.500              1

## Outlier Handling Decision

The IQR method was used to identify potential outliers in numeric variables.

An IQR outlier does not automatically mean that a value is incorrect. In a house-price dataset, unusually large houses, lots, garages, or sale prices can represent legitimate properties.

Therefore, the identified IQR outliers were reviewed rather than automatically deleted.

Values were retained when they were within a plausible real-world range for a house. Automatically removing all IQR outliers could remove legitimate high-value properties and introduce bias into the dataset.

No artificial values were created to reduce the number of outliers. The dataset retains legitimate extreme observations while documenting the detected outliers.

In [21]:
important_columns = [
    "LotArea",
    "GrLivArea",
    "TotalBsmtSF",
    "1stFlrSF",
    "GarageArea",
    "SalePrice"
]

for column in important_columns:
    if column in cleaned_df.columns:
        print(f"\n{column}")
        print("-" * len(column))
        print("Minimum:", cleaned_df[column].min())
        print("Maximum:", cleaned_df[column].max())

LotArea
-------
Minimum: 1300
Maximum: 215245

GrLivArea
---------
Minimum: 334
Maximum: 5642

TotalBsmtSF
-----------
Minimum: 0
Maximum: 6110

1stFlrSF
--------
Minimum: 334
Maximum: 4692

GarageArea
----------
Minimum: 0
Maximum: 1418

SalePrice
---------
Minimum: 34900.0
Maximum: 755000.0

In [22]:
checks = {
    "Negative LotArea": (cleaned_df["LotArea"] < 0).sum(),
    "Negative SalePrice": (cleaned_df["SalePrice"] < 0).sum(),
    "Negative GrLivArea": (cleaned_df["GrLivArea"] < 0).sum(),
    "Invalid MoSold": (
        (~cleaned_df["MoSold"].between(1, 12))
    ).sum(),
    "Invalid YearSold": (
        (~cleaned_df["YrSold"].between(2000, 2020))
    ).sum()
}

for check, count in checks.items():
    print(f"{check}: {count}")

Negative LotArea: 0
Negative SalePrice: 0
Negative GrLivArea: 0
Invalid MoSold: 0
Invalid YearSold: 0

In [23]:
final_quality_report = pd.DataFrame({
    "Data_Type": cleaned_df.dtypes.astype(str),
    "Missing_Count": cleaned_df.isnull().sum(),
    "Missing_Percent": (
        cleaned_df.isnull().sum() / len(cleaned_df) * 100
    ).round(2),
    "Unique_Values": cleaned_df.nunique()
})

display(final_quality_report)

              Data_Type  Missing_Count  Missing_Percent  Unique_Values
Id                  str              0              0.0           1460
MSSubClass          str              0              0.0             15
MSZoning            str              0              0.0              5
LotFrontage     float64              0              0.0            115
LotArea           int64              0              0.0           1073
Street              str              0              0.0              2
Alley               str              0              0.0              3
LotShape            str              0              0.0              4
LandContour         str              0              0.0              4
Utilities           str              0              0.0              2
LotConfig           str              0              0.0              5
LandSlope           str              0              0.0              3
Neighborhood        str              0              0.0             25
Condition1          str              0              0.0              9
Condition2          str              0              0.0              8
BldgType            str              0              0.0              5
HouseStyle          str              0              0.0              8
OverallQual       int64              0              0.0             10
OverallCond       int64              0              0.0              9
YearBuilt         int64              0              0.0            112
YearRemodAdd      int64              0              0.0             61
RoofStyle           str              0              0.0              6
RoofMatl            str              0              0.0              8
Exterior1st         str              0              0.0             15
Exterior2nd         str              0              0.0             16
MasVnrType          str              0              0.0              4
MasVnrArea      float64              0              0.0            327
ExterQual           str              0              0.0              4
ExterCond           str              0              0.0              5
Foundation          str              0              0.0              6
BsmtQual            str              0              0.0              5
BsmtCond            str              0              0.0              5
BsmtExposure        str              0              0.0              5
BsmtFinType1        str              0              0.0              7
BsmtFinSF1        int64              0              0.0            637
BsmtFinType2        str              0              0.0              7
BsmtFinSF2        int64              0              0.0            144
BsmtUnfSF         int64              0              0.0            780
TotalBsmtSF       int64              0              0.0            721
Heating             str              0              0.0              6
HeatingQC           str              0              0.0              5
CentralAir          str              0              0.0              2
Electrical          str              0              0.0              5
1stFlrSF          int64              0              0.0            753
2ndFlrSF          int64              0              0.0            417
LowQualFinSF      int64              0              0.0             24
GrLivArea         int64              0              0.0            861
BsmtFullBath      int64              0              0.0              4
BsmtHalfBath      int64              0              0.0              3
FullBath          int64              0              0.0              4
HalfBath          int64              0              0.0              3
BedroomAbvGr      int64              0              0.0              8
KitchenAbvGr      int64              0              0.0              4
KitchenQual         str              0              0.0              4
TotRmsAbvGrd      int64              0              0.0             12
Functional          str              0              0.0              7
Fireplaces        int64              0              0.0              4
FireplaceQu         str              0              0.0              6
GarageType          str              0              0.0              7
GarageYrBlt     float64              0              0.0             98
GarageFinish        str              0              0.0              4
GarageCars        int64              0              0.0              5
GarageArea        int64              0              0.0            441
GarageQual          str              0              0.0              6
GarageCond          str              0              0.0              6
PavedDrive          str              0              0.0              3
WoodDeckSF        int64              0              0.0            274
OpenPorchSF       int64              0              0.0            202
EnclosedPorch     int64              0              0.0            120
3SsnPorch         int64              0              0.0             20
ScreenPorch       int64              0              0.0             76
PoolArea          int64              0              0.0              8
PoolQC              str              0              0.0              4
Fence               str              0              0.0              5
MiscFeature         str              0              0.0              5
MiscVal           int64              0              0.0             21
MoSold            int64              0              0.0             12
YrSold            int64              0              0.0              5
SaleType            str              0              0.0              9
SaleCondition       str              0              0.0              6
SalePrice       float64              0              0.0            663

In [24]:
after_rows = len(cleaned_df)
after_duplicates = cleaned_df.duplicated().sum()
after_nulls = cleaned_df.isnull().sum().sum()

summary = pd.DataFrame({
    "Metric": [
        "Row Count",
        "Total Missing Values",
        "Duplicate Rows"
    ],
    "Before Cleaning": [
        before_rows,
        before_nulls,
        before_duplicates
    ],
    "After Cleaning": [
        after_rows,
        after_nulls,
        after_duplicates
    ]
})

display(summary)

                 Metric  Before Cleaning  After Cleaning
0             Row Count             1460            1460
1  Total Missing Values             7829               0
2        Duplicate Rows                0               0

In [25]:
dtype_comparison = pd.DataFrame({
    "Before": df.dtypes.astype(str),
    "After": cleaned_df.dtypes.astype(str)
})

display(dtype_comparison)

                Before    After
Id               int64      str
MSSubClass       int64      str
MSZoning           str      str
LotFrontage    float64  float64
LotArea          int64    int64
Street             str      str
Alley              str      str
LotShape           str      str
LandContour        str      str
Utilities          str      str
LotConfig          str      str
LandSlope          str      str
Neighborhood       str      str
Condition1         str      str
Condition2         str      str
BldgType           str      str
HouseStyle         str      str
OverallQual      int64    int64
OverallCond      int64    int64
YearBuilt        int64    int64
YearRemodAdd     int64    int64
RoofStyle          str      str
RoofMatl           str      str
Exterior1st        str      str
Exterior2nd        str      str
MasVnrType         str      str
MasVnrArea     float64  float64
ExterQual          str      str
ExterCond          str      str
Foundation         str      str
BsmtQual           str      str
BsmtCond           str      str
BsmtExposure       str      str
BsmtFinType1       str      str
BsmtFinSF1       int64    int64
BsmtFinType2       str      str
BsmtFinSF2       int64    int64
BsmtUnfSF        int64    int64
TotalBsmtSF      int64    int64
Heating            str      str
HeatingQC          str      str
CentralAir         str      str
Electrical         str      str
1stFlrSF         int64    int64
2ndFlrSF         int64    int64
LowQualFinSF     int64    int64
GrLivArea        int64    int64
BsmtFullBath     int64    int64
BsmtHalfBath     int64    int64
FullBath         int64    int64
HalfBath         int64    int64
BedroomAbvGr     int64    int64
KitchenAbvGr     int64    int64
KitchenQual        str      str
TotRmsAbvGrd     int64    int64
Functional         str      str
Fireplaces       int64    int64
FireplaceQu        str      str
GarageType         str      str
GarageYrBlt    float64  float64
GarageFinish       str      str
GarageCars       int64    int64
GarageArea       int64    int64
GarageQual         str      str
GarageCond         str      str
PavedDrive         str      str
WoodDeckSF       int64    int64
OpenPorchSF      int64    int64
EnclosedPorch    int64    int64
3SsnPorch        int64    int64
ScreenPorch      int64    int64
PoolArea         int64    int64
PoolQC             str      str
Fence              str      str
MiscFeature        str      str
MiscVal          int64    int64
MoSold           int64    int64
YrSold           int64    int64
SaleType           str      str
SaleCondition      str      str
SalePrice        int64  float64

In [26]:
print("FINAL DATASET CHECK")
print("===================")

print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])
print("Missing values:", cleaned_df.isnull().sum().sum())
print("Duplicate rows:", cleaned_df.duplicated().sum())

print("\nData types:")
print(cleaned_df.dtypes.value_counts())

FINAL DATASET CHECK
===================
Rows: 1460
Columns: 81
Missing values: 0
Duplicate rows: 0

Data types:
str        45
int64      32
float64     4
Name: count, dtype: int64

In [27]:
output_file = "House Prices Cleaned.csv"

cleaned_df.to_csv(
    output_file,
    index=False
)

print(f"Cleaned dataset saved successfully as: {output_file}")

Cleaned dataset saved successfully as: House Prices Cleaned.csv

In [28]:
check_df = pd.read_csv("House Prices Cleaned.csv")

print("Saved file successfully loaded.")
print("Shape:", check_df.shape)
print("Missing values:", check_df.isnull().sum().sum())
print("Duplicate rows:", check_df.duplicated().sum())

display(check_df.head())

Saved file successfully loaded.
Shape: (1460, 81)
Missing values: 7480
Duplicate rows: 0

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500.0
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500.0
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500.0
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000.0
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000.0

### Summary
This task focuses on cleaning the House Prices dataset using Python, Pandas, and NumPy. The process includes identifying missing values, duplicates, inconsistent data types, and outliers; applying appropriate methods to handle these issues; standardizing the data; and documenting each cleaning decision. Finally, the cleaned dataset is compared with the original dataset and saved as a new CSV file for further analysis.